### ISSUE TITLE
Molecule v3 schema: PlatformModel bugs

### ISSUE THREAD

**Issue by arturmartins** [ansible-community/schemas#85] opened 2021-08-05 18:00 UTC
I get the following error for valid `platform:` properties:
![Screenshot 2021-08-05 at 18 57 22](https://user-images.githubusercontent.com/101411/128398648-bd7778a0-f602-43fc-89c6-b8987bf30b4f.png)

networks: 
https://github.com/ansible-community/molecule/blob/386f5af4b2e896f4fa0bf87f6235e7d7e3d22480/src/molecule/model/schema_v3.py#L288

tty:
https://github.com/ansible-community/molecule/blob/386f5af4b2e896f4fa0bf87f6235e7d7e3d22480/src/molecule/model/schema_v3.py#L261

capacities:
https://github.com/ansible-community/molecule/blob/386f5af4b2e896f4fa0bf87f6235e7d7e3d22480/src/molecule/model/schema_v3.py#L268

**Comment by ssbarnea** [comment] 2022-02-16 10:36
Duplicate of #83

**Closed by ssbarnea** 2022-02-16 10:36 UTC
