### ISSUE TITLE
YAML schema validation is broken out of the box (Windows)

### ISSUE THREAD

**Issue by varnav** [ansible-community/schemas#37] opened 2021-04-27 15:43 UTC
Fresh Windows 10 installation (system) of 1.55.2

```
%UserProfile%\.vscode
%AppData%\Code
%LocalAppData%\Programs\Microsoft VS Code
```

were emptied before installation.

Only this extension is installed with dependencies.

I am trying to edit my task files and getting validation errors like:

```powershell
Property community.windows.win_initialize_disk is not allowed.yaml-schema: TaskModel
Missing property "action".yaml-schema: TaskModel | BeremothTaskModel
Incorrect type. Expected "array".yaml-schema: Tags | BeremothTaskModel
```

Ansible task example:

```yaml
- name: Initialize additional disk
  community.windows.win_initialize_disk:
    disk_number: 2
  tags: preinstall
```

**Comment by ssbarnea** [comment] 2021-04-28 13:28
While this is documented in the readme, I will be trying to address it soon.

**Comment by ssbarnea** [comment] 2021-05-12 14:43
Few minutes ago I merged a change that enables all community modules. You may need to restart vscode to make it re-cache the schema.

**Closed by ssbarnea** 2021-05-12 14:43 UTC
Labels: bug

**Comment by DMW007** [comment] 2022-01-20 17:20
I got similiar errors and found out that `become: yes` is the cause. When I change it to `become: true`, all three errors are gone:

![grafik](https://user-images.githubusercontent.com/21245043/150389020-47f7b190-c975-42f2-9530-5edd06e7d127.png)

Very misleading error messages from VS Code. I'm on Linux (Manjaro) with VS Code 1.62.0. But I'm wondering why `yes` seems not a valid boolean for the validator. Even when the [official Ansible documentation](https://docs.ansible.com/ansible/latest/user_guide/become.html) says that we should use `yes` instead of the known boolean values like `true/false`.

**Comment by ssbarnea** [comment] 2022-01-20 17:57
Yep, the schema is more restrictive as it also follows ansible-lint guidelines. Basically is will accept less stuff than ansible itself which has a goal to keep things compatible. Just use standard true/false and you will be fine.

**Comment by ssbarnea** [comment] 2022-01-20 18:00
The `playbook` and `tasks` schemas have very limited and we would recommend users to use the ansible-language-server instead, which is not using these schemas. For other files is ok, as we use schemas but not for those two, for good reasons. Change the document language from from `yaml` to `ansible` on these docs and you should far better results.
